---
auth_token: KgZvwNeUGdvEjyp9kmXy
projects:
  # data-id: project/branch
  # base-app: base-app/master
  # testapp-mongodb: testapp-mongodb/mongoid3
  # or
  # data-id: project
  # testapp-sphinx: testapp-sphinx
  cohive: cohive
  coachme: coachme-web
